### ISSUE TITLE
placement of Log files seems inconsistent.

### ISSUE THREAD

**Issue by eleson2** [OpenMediaVault-Plugin-Developers/openmediavault-minidlna#18]
OMV 5.5.23-1 (Usul)
miniDLNA 5.0.5

minidlna.conf:
log_dir=/var/log

but at some point logs have been created in 
/var/log/minidlna    (There are files there, date fit with my installation, but are not updated. )
minidlna can't write to /var/log  minidlnad doesn't seem to have access. 

OMV UI doesn't respect minidlna.conf log_dir entry. 

So logs aren't created in expected locations, and created logs can't be read in UI.

**Comment by ryecoaaron** [comment]
/var/log is the default config file location for minidlna.  So, the plugin has always set it to that.  Sometime between the creation of the plugin many years ago and now, the plugin switched to using minidlna from the Debian repos instead of a package that I built from source.  I didn't realize that Debian changed the default log location to /var/log/minidlna/.  So, their systemd unit file is using that directory which is created by the unit file and minidlnad can use it.

And unfortunately the plugin would need to be changed to use a differnet log location since the log viewer is hard-coded to always look in /var/log/minidlna.log.

I will look at it but there are so many better options than minidlna now that the only reason I keep the plugin around is it is my reference plugin when porting to a new version of OMV.  The next version (already being worked on) will use docker in the background.  I'm not sure how the logging will work with that.

**Comment by eleson2** [comment]
Thanks, it is easily resolved in my end so it is definitely low-prio for me.
(My journey started out with Jellyfin in docker. but DLNA is all I need and I didn't get that to work.  Hence miniDLNA .)
